version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "22:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
